# Copyright 2024 Ibrahim Mbaziira
# SPDX-License-Identifier: MIT

name: Feature Request
description: File a feature request.
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you face?
      description: Please describe the problem you faced?
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe your proposed solution.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
